server:
  port: 8083
  servlet:
    context-path: /p2
    
spring:
  application: 
    name: pawroledp2
  datasource:
    driver-class-name: org.postgresql.Driver
    url: YOUR_URL_HERE
    username: YOUR_USERNAME_HERE
    password: YOUR_PASSWORD_HERE
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create
      
management:
  endpoints:
    web:
      exposure:
        include:
          - "beans"
          - "health"
          - "info"
   
   

    
  
